name: tpkg-server
version: "%VER%"
maintainer: tpkg-users@lists.sourceforge.net
description: tpkg package management and reporting server
bugreporting: https://sourceforge.net/tracker/?group_id=245750

###
# I've had lots of problems with supposedly minor gem version
# changes breaking things, so I take a very pessimistic view with
# gem version requirements (specifying an exact version).  Other
# dependencies get more leniency.
dependencies:
- name: mysql
  minimum_version: 5.1.0
  maximum_version: 5.1.9999
- name: tpkg
  minimum_version: 1.27
- name: logrotate
  minimum_version: 3.5
  maximum_version: 3.9999
- name: stunnel
  minimum_version: 4.0
  maximum_version: 4.9999
- name: nginx
  minimum_version: 0.6
  maximum_version: 0.6.9999
- name: gem-unicorn
  minimum_version: 0.7.0
  maximum_version: 0.7.0
# unicorn depends on rack but doesn't express that dependency in 0.7
# Eric says he added the dependency in 0.8, so we can remove this once 0.8 is released
- name: gem-rack
  minimum_version: 1.0.0
  maximum_version: 1.0.0
- name: gem-rails
  minimum_version: 2.2.2
  maximum_version: 2.2.2
- name: gem-mysql
  minimum_version: 2.7
  maximum_version: 2.7
- name: gem-facter
  minimum_version: 1.5.5
  maximum_version: 1.5.5
files:
- path: /opt/tpkg/tpkg/config/ssl-key.pem
  encrypt:
    precrypt: true
  posix:
    perms: 0400
- path: /opt/tpkg/tpkg/config/mysql-credentials
  encrypt:
    precrypt: true
  posix:
    perms: 0400
- path: /opt/tpkg/tpkg/config/database.yml
  encrypt:
    precrypt: true
  posix:
    owner: t
    perms: 0400
- path: /opt/tpkg/etc/init.d/tpkg-db
  init: {}
  posix:
    perms: 0555
- path: /opt/tpkg/etc/init.d/tpkg-app
  init: {}
  posix:
    perms: 0555
- path: /opt/tpkg/etc/init.d/tpkg-web
  init: {}
  posix:
    perms: 0555
- path: /opt/tpkg/etc/cron.d/tpkg_server
  crontab: {}
  posix:
    perms: 0444
- path: /opt/tpkg/tpkg/log
  posix:
    owner: t
- path: /opt/tpkg/tpkg/tmp/pids
  posix:
    owner: t
